const cron = require('node-cron');
const connection = require('../config/db.config');

class CronService {
  static startJobs() {
    // Chạy vào 00:01 mỗi ngày
    cron.schedule('1 0 * * *', async () => {
      console.log('🕐 [CRON] Starting daily tasks...');
      try {
        // 1. Apply pending work shift updates
        const WorkShiftModel = require('../models/workshift.model');
        await WorkShiftModel.applyPendingUpdates();
        
        // 2. Tự động checkout những timesheet quên checkout
        const DailyTimesheetModel = require('../models/dailyTimesheet.model');
        await DailyTimesheetModel.autoCheckoutForgottenTimesheets();
        
        // 3. Tạo timesheet mới cho ngày hôm nay
        await this.generateDailyTimesheets();
        
        console.log('✅ [CRON] Daily tasks completed');
      } catch (error) {
        console.error('❌ [CRON] Error in daily tasks:', error);
      }
    });

    console.log('✅ Cron jobs scheduled: Daily tasks at 00:01 (shift updates + auto checkout + timesheet generation)');
    
    // Uncomment để test ngay khi server start
    // this.generateDailyTimesheets();
  }

  static async generateDailyTimesheets(targetDate = null) {
    const workDate = targetDate || new Date().toISOString().split('T')[0];

    try {
      // 1. Lấy tất cả nhân viên active có department
      const [employees] = await connection.query(`
        SELECT e.employee_id, e.department_id, e.status
        FROM EMPLOYEE e
        WHERE e.status = 'active' AND e.department_id IS NOT NULL
      `);

      if (employees.length === 0) {
        console.log('ℹ️ [CRON] No active employees found');
        return { created: 0, skipped: 0, errors: 0 };
      }

      console.log(`📊 [CRON] Processing ${employees.length} employees for ${workDate}`);

      let created = 0;
      let skipped = 0;
      let errors = 0;

      // 2. Lấy work shifts cho tất cả departments
      const [workShifts] = await connection.query(`
        SELECT shift_id, department_id FROM WORK_SHIFT
      `);

      const shiftMap = {};
      workShifts.forEach(shift => {
        shiftMap[shift.department_id] = shift.shift_id;
      });

      // 3. Process từng nhân viên
      for (const emp of employees) {
        try {
          const shiftId = shiftMap[emp.department_id];

          if (!shiftId) {
            console.warn(`⚠️ [CRON] No work shift for department ${emp.department_id}`);
            skipped++;
            continue;
          }

          // Kiểm tra đã tồn tại chưa
          const [existing] = await connection.query(
            'SELECT 1 FROM DAILY_TIMESHEET WHERE employee_id = ? AND work_date = ?',
            [emp.employee_id, workDate]
          );

          if (existing.length > 0) {
            skipped++;
            continue;
          }

          // Tạo timesheet mới
          await connection.query(`
            INSERT INTO DAILY_TIMESHEET 
            (employee_id, work_date, shift_id, check_in_time, check_out_time, 
             minutes_late, minutes_early, notes, adjusted_by_employee_id)
            VALUES (?, ?, ?, NULL, NULL, 0, 0, 'Auto-generated by system', NULL)
          `, [emp.employee_id, workDate, shiftId]);

          created++;
        } catch (err) {
          console.error(`❌ Error creating timesheet for ${emp.employee_id}:`, err.message);
          errors++;
        }
      }

      console.log(`✅ [CRON] Created: ${created}, Skipped: ${skipped}, Errors: ${errors}`);

      return { created, skipped, errors };
    } catch (error) {
      console.error('❌ [CRON] Fatal error:', error);
      throw error;
    }
  }

  // Manual trigger
  static async manualTrigger(date) {
    const targetDate = date || new Date().toISOString().split('T')[0];
    console.log(`🔧 [MANUAL] Generating timesheets for ${targetDate}`);
    return this.generateDailyTimesheets(targetDate);
  }
}

module.exports = CronService;
